---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: metallb-system
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1m
  chart:
    spec:
      chart: metallb
      version: 6.4.19
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: metallb-system
  values:
    speaker:
      enabled: true
    controller:
      enabled: true
