#cloud-config

ssh_pwauth: false

users:
  - name: ansible
    gecos: Ansible User
    groups: users,admin,wheel
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu"

  - name: axel
    gecos: Axel Nemes
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: true
    passwd: $6$tuL0SaSX2SJJyyFh$Zae2ac0X4vXcyPs.AEOpIEoP6oaXCmnW36gNwfR4sdXd7rbB358DXnK7nv0dG54Yfi5AXQYD7ODjgzUBe/rgM1
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu"
runcmd:
  - apt-get update
  - apt-get install qemu-guest-agent -y
  - systemctl start qemu-guest-agent
