---
ansible_ssh_pass: Asdasd11

# Common Users:             2000-3000
# Host specific Users:      3001-4000
# Service Users:            5000-6000
# Common Groups:            10000-11000
# Host specific Groups:     11001-12000

lock_all_users: false
common_posix_folders:
  - path: /common_storage
    owner: root
    group: root
    mode: 775
    acls: []

common_posix_users:
  - uid: 2001
    name: alice
    comment: Alice Anderson
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      # axel@ubuntu
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
      # peter@osboxes
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs8+5dNkrbOX7Pg3OrJ7Vnxc4JtzAoeuNgGOM03jmHxWXZP2cHPmCI0gsDTaBU4jN+wn58g/Cgy/hFYK8MA9NIFgp9NRqetfJaRnK1eN15X+/1j1jst9Uc5imFpKmWsi1Sidg/nE0WjxhQrU+8XZ4EBXxxlK6CBIoKot5KJtUZFtjuq8i6tA9Eb4hDb3nRtmIrQmPLkh7wLuiT20dvOZ2LoW0pRzrsRrz7Q6//amg0jBZji7uva23ZFP/VvADKJUEgQO8naFSc7kkShuUKvY60inyR1trp6fORNqCeqNlEZDjJq9KC7wWXYln1ZJTyLo2brDkWNuWXk4T8fPYxEczj ansible-generated on osboxes
        enabled: true
    locked: false
    samba_access: true

  - uid: 2002
    name: peter
    comment: Peter Griffin
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
    locked: false

common_posix_groups: []

merged_posix_folders: "{{ common_posix_folders + (posix_folders | default([], true)) }}"
merged_posix_users: "{{ common_posix_users + (posix_users | default([], true)) }}"
merged_posix_groups: "{{ common_posix_groups + (posix_groups | default([], true)) }}"
