---
ansible_ssh_pass: Asdasd11

# Common Users:             2000-3000
# Host specific Users:      3001-4000
# Service Users:            5000-6000
# Common Groups:            10000-11000
# Host specific Groups:     11001-12000

lock_all_users: false
common_posix_folders:
  - path: /common_storage
    owner: root
    group: root
    mode: 775
    acls: []

common_posix_users:
  - uid: 2001
    name: axel
    comment: Axel Roland Nemes
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      # axel@ubuntu
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
      # axel@thinkpad
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCum76H/eFrhuRewSNHdd74NmaMWpO2yzwJ/l5UNMxggqYPZSojWNGhczwaayX1Olb653C4lc+JRsjLIcR75PeBAJ4SKre/63ORCDwvAXsaCsNRQYgruEFDZ0+ATViAPyuJOPSKTGsXPdTNd7Q2cxZgyLvOEaES+Qy+caVNDbM++j9falI2/l0FbmbRdzXFlzDGYa4V1BIa+eL69ERc4sqgPt40C4RRhe+El/s/kaBymC0I5RC9yejRnRB+0k2OF5XFNqwd9JY8fzZlasnSvv8UZM7xvbxoFkH+wMqJZ1eE4OuZgxJ4hlBbOS20sbZ4xyNsnO7Mv0Ag2DRLZI+u7t6n+c0Vu/GrNgJfVOuScNiTVCqmQaLb7wGk1BDfGk7ztnlB7S3kZHh3bXxsk11d98/HTtJDAsutwAWQym6odxZ4CxtZwH6mfQyU+a8EOkpfHGag539Cicm/xLk5KmTkfRfPxQa1abKA41OPWqI8D1LLdEjIXpe8jDuvqIDnHERibKU= axel@thinkpad
        enabled: true
    locked: false
    samba_access: true

  - uid: 2002
    name: bob
    comment: Bob Anderson
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      # axel@ubuntu
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
      # axel@thinkpad
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCum76H/eFrhuRewSNHdd74NmaMWpO2yzwJ/l5UNMxggqYPZSojWNGhczwaayX1Olb653C4lc+JRsjLIcR75PeBAJ4SKre/63ORCDwvAXsaCsNRQYgruEFDZ0+ATViAPyuJOPSKTGsXPdTNd7Q2cxZgyLvOEaES+Qy+caVNDbM++j9falI2/l0FbmbRdzXFlzDGYa4V1BIa+eL69ERc4sqgPt40C4RRhe+El/s/kaBymC0I5RC9yejRnRB+0k2OF5XFNqwd9JY8fzZlasnSvv8UZM7xvbxoFkH+wMqJZ1eE4OuZgxJ4hlBbOS20sbZ4xyNsnO7Mv0Ag2DRLZI+u7t6n+c0Vu/GrNgJfVOuScNiTVCqmQaLb7wGk1BDfGk7ztnlB7S3kZHh3bXxsk11d98/HTtJDAsutwAWQym6odxZ4CxtZwH6mfQyU+a8EOkpfHGag539Cicm/xLk5KmTkfRfPxQa1abKA41OPWqI8D1LLdEjIXpe8jDuvqIDnHERibKU= axel@thinkpad
        enabled: true
    locked: false
    samba_access: true

  - uid: 2003
    name: peter
    comment: Peter Griffin
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      # axel@ubuntu
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
      # axel@thinkpad
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCum76H/eFrhuRewSNHdd74NmaMWpO2yzwJ/l5UNMxggqYPZSojWNGhczwaayX1Olb653C4lc+JRsjLIcR75PeBAJ4SKre/63ORCDwvAXsaCsNRQYgruEFDZ0+ATViAPyuJOPSKTGsXPdTNd7Q2cxZgyLvOEaES+Qy+caVNDbM++j9falI2/l0FbmbRdzXFlzDGYa4V1BIa+eL69ERc4sqgPt40C4RRhe+El/s/kaBymC0I5RC9yejRnRB+0k2OF5XFNqwd9JY8fzZlasnSvv8UZM7xvbxoFkH+wMqJZ1eE4OuZgxJ4hlBbOS20sbZ4xyNsnO7Mv0Ag2DRLZI+u7t6n+c0Vu/GrNgJfVOuScNiTVCqmQaLb7wGk1BDfGk7ztnlB7S3kZHh3bXxsk11d98/HTtJDAsutwAWQym6odxZ4CxtZwH6mfQyU+a8EOkpfHGag539Cicm/xLk5KmTkfRfPxQa1abKA41OPWqI8D1LLdEjIXpe8jDuvqIDnHERibKU= axel@thinkpad
        enabled: true
    locked: false
    samba_access: true

common_posix_groups: []

merged_posix_folders: "{{ common_posix_folders + (posix_folders | default([], true)) }}"
merged_posix_users: "{{ common_posix_users + (posix_users | default([], true)) }}"
merged_posix_groups: "{{ common_posix_groups + (posix_groups | default([], true)) }}"
