---
samba_shares:
  - name: storage
    path: /storage
    samba_browsable: true
    samba_name: Root Storage
    samba_valid_users:
      - "@storage_ro"
      - "@storage_rw"

  - name: common
    path: /storage/common
    samba_browsable: true
    samba_name: Common stuff
    samba_valid_users:
      - "@common_ro"
      - "@common_rw"

  - name: safe
    path: /storage/safe
    samba_browsable: true
    samba_name: Safe
    samba_valid_users:
      - "@safe_ro"
      - "@safe_rw"
      - "@common_ro"
