ansible_user: ansible
ansible_host: 192.168.1.14
ansible_port: 22

posix_folders:
  - path: /storage
    owner: root
    group: root
    mode: 770
    acls:
      - { etype: group, entity: storage_ro, perms: rx }
      - { etype: group, entity: storage_rw, perms: rwx }

  - path: /storage/common
    owner: root
    group: root
    mode: 770
    acls:
      - { etype: group, entity: common_ro, perms: rx }
      - { etype: group, entity: common_rw, perms: rwx }

  - path: /storage/safe
    owner: root
    group: root
    mode: 770
    acls:
      - { etype: group, entity: safe_ro, perms: rx }
      - { etype: group, entity: safe_rw, perms: rwx }

posix_users:
  - uid: 3001
    name: jerry
    comment: Jerry Smith
    create_home: true
    password: "Asdasd22"
    shell: /bin/bash
    generate_ssh_key: true
    authorized_keys:
      # axel@ubuntu
      - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkoawvCBBV/eRY17Zkv440xtWKbcjwT+yrZr3kVWa/Z6dtPd58S/WZ5FZ5sWVkzr78P7hZJiHxU4ISmNEANcJFOMz5X1LF+gSfk0Qkba431Qq0I6ODODNCcCo90no/P0ml0kyhcqNPkfH8WIlcYpQ3w0PV9q0bM3xDDP/HVXlYzSzz0xLOS/Vqjqa2AbUXQdIdtPszuSaw+DFbaTg2wVQIAegzF3tzlj/qEE8gsMd7dQ2S/FZXp1Nr1lGFI3ZeGhy66F75o7ysa46ua7sHZJYCpdDs9wX2coQRams95aSTwnIlSbjZE72oo2SMrNV4JKsPe23/db6Yi6LEb3p7zF9bDV/HPjhZeiGdEd66najWsLAuIgoYabTdmI/4q6NZMflnvcIQeD646Q5Bof4Y02ldixqZ8iodzHd+4FRWbztb/wQZvTiqPvcSDpwUmrBklmgnNao0s+tZShZfask+Y3R2M192cwkMKIImQysbBZvuKI/NgO5oiqqgS6cvZLdQchE= axel@ubuntu
        enabled: false
    locked: false
    samba_access: true

posix_groups:
  - name: storage_ro
    gid: 11001
    users: []
  - name: storage_rw
    gid: 11002
    users: []

  - name: common_ro
    gid: 11003
    users: []
  - name: common_rw
    gid: 11004
    users: []

  - name: films_ro
    gid: 11005
    users: []
  - name: films_rw
    gid: 11006
    users: []

  - name: workspace_ro
    gid: 11007
    users: []
  - name: workspace_rw
    gid: 11008
    users: []

  - name: safe_ro
    gid: 11009
    users: []
  - name: safe_rw
    gid: 11010
    users: []
